{% set name = "wagtail-ai" %}
{% set version = "1.1.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/wagtail_ai-{{ version }}.tar.gz
  sha256: bae9a130f31b7a4f35e5776ede6d8f302672477c49b2c79adc6680cb16cdf261

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8
    - flit-core >=3.2,<4
    - pip
    - django >=3.0
  run:
    - python >=3.8
    - django >=3.0
    - wagtail >=4.0
    - langchain >=0.0.106
    - tiktoken >=0.3.0

test:
  commands:
    - python -c "import django; from django.conf import settings; settings.configure(); django.setup(); import wagtail_ai"
    - pip check
  requires:
    - pip

about:
  home: https://github.com/wagtail/wagtail-ai
  summary: Get a hand writing your content with AI super powers!
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rxm7706
