{% set name = "wagtail-ai" %}
{% set version = "3.0.0" %}
{% set python_min = "3.11" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/wagtail_ai-{{ version }}.tar.gz
  sha256: 4e1dd7c8dc6dc7a2a0a2a26a13536a61834cbcce9723500996287409b4176937

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - flit-core >=3.2,<4
    - pip
  run:
    - django-ai-core
    - python >={{ python_min }}
    - django >=4.2
    - wagtail >=7.1
    - llm >=0.12

test:
  imports:
    - wagtail_ai
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/wagtail/wagtail-ai
  summary: Get a hand writing your content with AI super powers!
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rxm7706
