{% set name = "wagtail-ai" %}
{% set version = "2.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/wagtail_ai-{{ version }}.tar.gz
  sha256: 7637643a5496e6e6b32003155d7eb5a02978cf230293a2594f9ec32b69b031a5

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8
    - flit-core >=3.2,<4
    - pip
  run:
    - python >=3.8
    - django >=4.2
    - wagtail >=5.2
    - llm >=0.12

test:
  imports:
    - wagtail_ai
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/wagtail/wagtail-ai
  summary: Get a hand writing your content with AI super powers!
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rxm7706
